ci:
   autoupdate_schedule: quarterly
   autofix_prs: false

repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args:
          - --fix
          - --disable=MD041
          - --disable=MD033
